---
title: "aim2_modelevaluation"
output: html_document
date: "2025-02-23"
---

```{r setup, include=FALSE}
library(readxl)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(gt)
library(broom)
library(plotly)
summary.per <- read_excel("~/Downloads/aim2.xlsx", sheet = "Calculation.new") %>% rename("ES"=c(1))
summary.per <- read_excel("~/Downloads/aim2.xlsx", sheet = "Calculation.new") %>% rename("ES"=c(1))

################################################################----------------
#---------plot sensitivity vs type 1 error: (using 19 different significant alpha thresholds)
alpha_thres=list(0,0.00001,0.0009,0.004,0.005,0.006,0.008,0.01,0.02,0.03,0.05,0.1,0.2,0.375,0.5,0.6,0.8,0.9,1)

#---generate a function to calculate TPR:
func.sensitivity=function(true.positive, false.negative) {
  return(true.positive/(true.positive+false.negative)) }

#---generate a function to calculate type 1 error:
func.type1error=function(false.positive, true.negative) {
  return(false.positive/(false.positive+true.negative))
}

#---apply functions on ES=0.4
all_med=summary.per %>% filter(ES==0.4) 
true.positive_med=lapply(alpha_thres, function(x) all_med %>%
                           filter(`p-value/PERMANOVA`< x) %>%
                           nrow(.)) 
false.positive_med=lapply(alpha_thres, function(x) all_med %>% 
                            filter(`p-value/PERMANOVA-NG`< x) %>% 
                            nrow(.))
false.negative_med=lapply(alpha_thres, function(x) all_med %>% 
                            filter(`p-value/PERMANOVA` >= x) %>% 
                            nrow(.))
true.negative_med=lapply(alpha_thres, function(x) all_med %>% 
                            filter(`p-value/PERMANOVA-NG` >= x) %>% 
                            nrow(.))

#---apply functions on ES=0.8
all_large=summary.per %>% filter(ES==0.8)
true.positive_large=lapply(alpha_thres, function(x) all_large %>%
                           filter(`p-value/PERMANOVA`< x) %>%
                           nrow(.)) 
false.positive_large=lapply(alpha_thres, function(x) all_large %>% 
                            filter(`p-value/PERMANOVA-NG`< x) %>% 
                            nrow(.))
false.negative_large=lapply(alpha_thres, function(x) all_large %>% 
                            filter(`p-value/PERMANOVA` >= x) %>% 
                            nrow(.))
true.negative_large=lapply(alpha_thres, function(x) all_large %>% 
                            filter(`p-value/PERMANOVA-NG` >= x) %>% 
                            nrow(.))

#---apply functions on ES=0.2
all_small=summary.per %>% filter(ES==0.2)
true.positive_small=lapply(alpha_thres, function(x) all_small %>%
                           filter(`p-value/PERMANOVA`< x) %>%
                           nrow(.)) 
false.positive_small=lapply(alpha_thres, function(x) all_small %>% 
                            filter(`p-value/PERMANOVA-NG`< x) %>% 
                            nrow(.))
false.negative_small=lapply(alpha_thres, function(x) all_small %>% 
                            filter(`p-value/PERMANOVA` >= x) %>% 
                            nrow(.))
true.negative_small=lapply(alpha_thres, function(x) all_small %>% 
                            filter(`p-value/PERMANOVA-NG` >= x) %>% 
                            nrow(.))

#---apply functions on combined ES:
true.positive_all=lapply(alpha_thres, function(x) summary.per %>%
                           filter(`p-value/PERMANOVA`< x) %>%
                           nrow(.)) 
false.positive_all=lapply(alpha_thres, function(x) summary.per %>% 
                            filter(`p-value/PERMANOVA-NG`< x) %>% 
                            nrow(.))
false.negative_all=lapply(alpha_thres, function(x) summary.per %>% 
                            filter(`p-value/PERMANOVA` >= x) %>% 
                            nrow(.))
true.negative_all=lapply(alpha_thres, function(x) summary.per %>% 
                            filter(`p-value/PERMANOVA-NG` >= x) %>% 
                            nrow(.))

#---calculate for fpr and tpr:
fpr.med=mapply(func.type1error,
               false.positive_med, true.negative_med)
fpr.large=mapply(func.type1error,
               false.positive_large, true.negative_large)
fpr.small=mapply(func.type1error,
               false.positive_small, true.negative_small)
fpr.all=mapply(func.type1error,
               false.positive_all, true.negative_all)

tpr.med=mapply(func.sensitivity,
               true.positive_med, false.negative_med)
tpr.large=mapply(func.sensitivity,
                 true.positive_large, false.negative_large)
tpr.small=mapply(func.sensitivity,
                 true.positive_small, false.negative_small)
tpr.all=mapply(func.sensitivity,
                 true.positive_all, false.negative_all)

#make auc:
fdr.tpr_small.es=data.frame(
  tpr=tpr.small,
  fpr=fpr.small,
  es="small")
  
fdr.tpr_med.es=data.frame(
  tpr=tpr.med,
  fpr=fpr.med,
  es="medium")

fdr.tpr_large.es=data.frame(
  tpr=tpr.large,
  fpr=fpr.large,
  es="large")

fdr.tpr_all.es=data.frame(
  tpr=tpr.all,
  fpr=fpr.all,
  es="all")

#manual calculate for auc
auc_med=sum(diff(fdr.tpr_med.es$fpr) * (head(fdr.tpr_med.es$tpr, -1) + tail(fdr.tpr_med.es$tpr, -1)) / 2) 
auc_large=sum(diff(fdr.tpr_large.es$fpr)* (head(fdr.tpr_large.es$tpr, -1) + tail(fdr.tpr_large.es$tpr, -1)) / 2) 
auc_small=sum(diff(fdr.tpr_small.es$fpr)* (head(fdr.tpr_small.es$tpr, -1) + tail(fdr.tpr_small.es$tpr, -1)) / 2) 
auc_all=sum(diff(fdr.tpr_all.es$fpr) * (head(fdr.tpr_all.es$tpr, -1) + tail(fdr.tpr_all.es$tpr, -1)) / 2) 

roc.df_1=rbind(fdr.tpr_large.es, fdr.tpr_small.es, fdr.tpr_med.es, fdr.tpr_all.es) %>% cbind(unlist(alpha_thres)) %>% mutate(alpha_lev=ifelse(alpha==0.05,"at 0.05","other"))

ggplot(roc.df_1, aes(x = fpr, y = tpr, color = es, shape = alpha_lev)) +
  geom_point(size = 3, stroke=0.35) +  # Adjust point size and stroke for visibility
  geom_line(aes(group = interaction(es, alpha_lev)), linewidth = 1) +  # Connect points with lines
  scale_shape_manual(values = c(16, 1)) +
  labs(title="AUC-ROC for Different Effect Size", x="False Positive Rate", y="True Positive Rate", size=3) +
  scale_color_manual(values=c("#ac2e44", "#104176", "#f55724","#72ccae"))+
  geom_abline(slope = 1, intercept = 0, linetype="dashed") +
  theme(legend.position="bottom",       
        panel.grid = element_line(color = "lightgray"),  # Set grid lines to light gray
        panel.background = element_blank(),         # Remove grid lines
        plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size=12)) +
  annotate("text", x = 0.7, y = 0.5,                          
           label = paste("AUC (all ES) =", round(auc_all, 2)), 
           color = "#ac2e44", size = 4) +
  annotate("text", x = 0.7, y = 0.4,                          
           label = paste("AUC (ES=0.8) =", round(auc_large, 2)), 
           color = "#104176", size = 4) +
  annotate("text", x = 0.7, y = 0.3,                          
           label = paste("AUC (ES=0.4) =", round(auc_med, 2)), 
           color = "#f55724", size = 4) +
  annotate("text", x = 0.7, y = 0.2,                          
           label = paste("AUC (ES=0.2) =", round(auc_small, 2)), 
           color = "#72ccae", size = 4) 


  
```


```{r cars}
#--rsquare correlation f-statistic (in order to use as a representation for ES)
```


```{r conflicting-results}
#---ROC for conflicting vs non-conflicting:
sm1=summary.per %>% filter(SM==1)
conf=sm1 %>% filter(`conflicting genes`!=0) 
nonconf=sm1 %>% filter(`conflicting genes`==0)

#apply to conflicting:
true.positive_conf=lapply(alpha_thres, function(x) conf %>%
                           filter(`p-value/PERMANOVA`< x) %>%
                           nrow(.))
false.positive_conf=lapply(alpha_thres, function(x) conf %>% 
                            filter(`p-value/PERMANOVA-NG`< x) %>% 
                            nrow(.))
false.negative_conf=lapply(alpha_thres, function(x) conf %>% 
                            filter(`p-value/PERMANOVA` >= x) %>% 
                            nrow(.))
true.negative_conf=lapply(alpha_thres, function(x) conf %>% 
                            filter(`p-value/PERMANOVA-NG` >= x) %>% 
                            nrow(.))

#apply to nonconflicting:
true.positive_nonconf=lapply(alpha_thres, function(x) nonconf %>%
                           filter(`p-value/PERMANOVA`< x) %>%
                           nrow(.))
false.positive_nonconf=lapply(alpha_thres, function(x) nonconf %>% 
                            filter(`p-value/PERMANOVA-NG`< x) %>% 
                            nrow(.))
false.negative_nonconf=lapply(alpha_thres, function(x) nonconf %>% 
                            filter(`p-value/PERMANOVA` >= x) %>% 
                            nrow(.))
true.negative_nonconf=lapply(alpha_thres, function(x) nonconf %>% 
                            filter(`p-value/PERMANOVA-NG` >= x) %>% 
                            nrow(.))

#---calculate for fpr and tpr:
fpr.nonconf=mapply(func.type1error,
               false.positive_nonconf, true.negative_nonconf)
fpr.conf=mapply(func.type1error,
               false.positive_conf, true.negative_conf)

tpr.nonconf=mapply(func.sensitivity,
               true.positive_nonconf, false.negative_nonconf)
tpr.conf=mapply(func.sensitivity,
                 true.positive_conf, false.negative_conf)

#---make auc:
fdr.tpr_conf=data.frame(
  tpr=tpr.conf,
  fpr=fpr.conf,
  group="conflicting"
)

fdr.tpr_nonconf=data.frame(
  tpr=tpr.nonconf,
  fpr=fpr.nonconf,
  group="non-conflicting"
)
roc_conf=rbind(fdr.tpr_conf, fdr.tpr_nonconf) %>% cbind(unlist(alpha_thres)) %>% mutate(alpha_lev=ifelse(`unlist(alpha_thres)`==0.05,"at 0.05","other"))

auc_conf=sum(diff(fdr.tpr_conf$fpr) * (head(fdr.tpr_conf$tpr, -1) + tail(fdr.tpr_conf$tpr, -1)) / 2) 
auc_nonconf=sum(diff(fdr.tpr_nonconf$fpr) * (head(fdr.tpr_nonconf$tpr, -1) + tail(fdr.tpr_nonconf$tpr, -1)) / 2) 

ggplot(roc_conf, aes(x = fpr, y = tpr, color = group, shape = alpha_lev)) +
  geom_point(size = 3, stroke=0.3) +  # Adjust point size and stroke for visibility
  geom_line(aes(group = interaction(group, alpha_lev)), linewidth = 1) +  # Connect points with lines
  scale_shape_manual(values = c(16, 1)) +
  labs(title="AUC-ROC for Conflicting vs Non-conflicting Design", x="False Positive Rate", y="True Positive Rate", size=3) +
  scale_color_manual(values=c("#ac2e44", "#104176"))+
  geom_abline(slope = 1, intercept = 0, linetype="dashed") +
  theme(legend.position="bottom",       
        panel.grid = element_line(color = "lightgray"),  # Set grid lines to light gray
        panel.background = element_blank(),         # Remove grid lines
        plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size=12)) +
  annotate("text", x = 0.7, y = 0.5,                          
           label = paste("AUC (conflicting) =", round(auc_conf, 2)), 
           color = "#ac2e44", size = 4) +
  annotate("text", x = 0.7, y = 0.4,                          
           label = paste("AUC (non-conflicting) =", round(auc_nonconf, 2)), 
           color = "#104176", size = 4) 

#at ES=0.4, 0.2, and 0.8 and alpha=0.05
es.level=list(0.4)

#conflicting:
alles_conf=lapply(es.level, function(x) filter(conf, ES==x))
alles_conf_tpr=lapply(alles_conf, function(x) func.sensitivity(
  nrow(filter(x, `p-value/PERMANOVA`<0.05)),
  nrow(filter(x, `p-value/PERMANOVA`>=0.05))
))

alles_conf_fpr=lapply(alles_conf, function(x) func.type1error(
  nrow(filter(x, `p-value/PERMANOVA-NG`<0.05)),
  nrow(filter(x, `p-value/PERMANOVA-NG`>=0.05))
)) 

#nonconflicting:
alles_nonconf=lapply(es.level, function(x) filter(nonconf, ES==x))
alles_nonconf_tpr=lapply(alles_nonconf, function(x) func.sensitivity(
  nrow(filter(x, `p-value/PERMANOVA`<0.05)),
  nrow(filter(x, `p-value/PERMANOVA`>=0.05))
))

alles_nonconf_fpr=lapply(alles_nonconf, function(x) func.type1error(
  nrow(filter(x, `p-value/PERMANOVA-NG`<0.05)),
  nrow(filter(x, `p-value/PERMANOVA-NG`>=0.05))
))


disc=data.frame(
  model="non-conflicting",
  metric=c("TPR","FPR"),
  value=rbind(unlist(alles_nonconf_tpr),
             unlist(alles_nonconf_fpr))
) %>% rbind(data.frame(
  model="conflicting",
  metric=c("TPR", "FPR"),
  value=rbind(unlist(alles_conf_tpr),
              unlist(alles_conf_fpr))
))

#bar plot 
ggplot(disc, aes(x = model, y = value, fill = metric)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9), width = 0.6) +
  geom_text(aes(label = round(value, 2)), 
            vjust = -0.5, 
            position = position_dodge(width = 0.8), 
            size = 4) + 
  scale_fill_manual(values = c("#ae282c","#003366")) +  # Custom colors
  labs(title = "Conflicting vs Non-conflicting Performance at Medium ES",
       x = "Model",
       y = "Value",
       fill = "Metric") +
   theme(legend.position="bottom",       
        panel.grid = element_line(color = "lightgray"),  # Set grid lines to light gray
        panel.background = element_blank(),         # Remove grid lines
        plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.text.x = element_text(size = 11),
        axis.title.y = element_text(size=11))

```
